name: topomapper
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  logger: ^2.0.2+1
  flutter_map: ^6.1.0
  url_launcher: ^6.2.5
  flutter_map_location_marker: ^8.0.8
  geolocator: ^11.0.0
  latlong2: ^0.9.0
  flutter_dotenv: ^5.1.0
  http: ^1.2.0
  flutter_map_marker_cluster: ^1.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets: 
    - assets/
    - config.env

